### ISSUE TITLE
Parsing Error in relation to Scraping dates for Hubble Images

### ISSUE THREAD

**Issue by shiroininjaTech** [shiroininjaTech/AstroNinja-Alpha#13]
Hey guys, Tom here. Before I left for my honeymoon, I received an error in AstroNinja that caused a crash of the app at launch. When I returned from our trip, the issue persisted, so I'm opening an issue. I haven't had a lot of time to look at it yet, but I think it has to do with maybe some changes to the source site for hubble images. It looks like the objects Scrapy searches for no longer contains the same data as before. I also want to test this with print statements of the lists passed from Scrapy to the data processing module, HubbleViews. 

`Traceback (most recent call last):
  File "AstroNinjaMain.py", line 1328, in <module>
    ex = App()
  File "AstroNinjaMain.py", line 109, in __init__
    self.initUI()
  File "AstroNinjaMain.py", line 991, in initUI
    xNewsV85.hubbleViewz(HubblesortingSelected)
 
 File "/home/shiroininja/Documents/PythonFiles/web_scraping/AstroNinja/xNewsV85.py", line 99, in hubbleViewz
    sortedResults = sorted(hubbleData, key = lambda i: parser.parse(i['hubbleDate']), reverse=True)
  File "/home/shiroininja/Documents/PythonFiles/web_scraping/AstroNinja/xNewsV85.py", line 99, in <lambda>
    sortedResults = sorted(hubbleData, key = lambda i: parser.parse(i['hubbleDate']), reverse=True)
  File "/home/shiroininja/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/shiroininja/.local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ParserError("Unknown string format: %s", timestr)`

**Comment by shiroininjaTech** [comment]
Issue solved by accounting for missing objects in the metadata for Hubble images
