### ISSUE TITLE
Getting an IndexError in spaceXlaunch module

### ISSUE THREAD

**Issue by shiroininjaTech** [shiroininjaTech/AstroNinja-Alpha#14]
Hey guys, 

It appears I released that update a bit too early, and there appears to be some bugs I hadn't done enough testing to catch. This will cause AstroNinja to not launch. It's most likely caused by there not being a launch video available for the most recent launch or a format change in the source. In either case, a switch/if statement will need to be written to catch it. 

I haven't had a lot a time to work on the project lately, so It might have to wait until the weekend.
Tom

```
Traceback (most recent call last):
  File "/home/shiroininja/.AstroNinja/AstroNinjaMain.py", line 1331, in <module>
    ex = App()
  File "/home/shiroininja/.AstroNinja/AstroNinjaMain.py", line 109, in __init__
    self.initUI()
  File "/home/shiroininja/.AstroNinja/AstroNinjaMain.py", line 644, in initUI
    spaceXlaunch.liftOff()
  File "/home/shiroininja/.AstroNinja/spaceXlaunch.py", line 38, in liftOff
    onlyLink = link[0]
IndexError: list index out of range
```

**Comment by shiroininjaTech** [comment]
So, the app is working again. It must definitely be an issue of not having a launch video available and I not coding for that scenario. Now that there has been another launch, it loads again.

**Comment by shiroininjaTech** [comment]
Ok, I've uploaded a fix for the issue that basically checks if the video url variable is empty and doesn't load the Launch lens if that is the case. I will keep this issue open while the update is being tested.
